#!/usr/bin/env python3
"""Build js/data/sky-data.js from the d3-celestial catalog (BSD-3-Clause, Olaf Frohn).

Usage:
    npm pack d3-celestial@0.7.35 && tar xzf d3-celestial-0.7.35.tgz
    python3 tools/build_sky_data.py package/data

Output is a compact JS file so the app works offline and from file:// without fetch().
"""
import json
import math
import os
import sys

MAG_LIMIT = 5.5
OUT = os.path.join(os.path.dirname(__file__), '..', 'js', 'data', 'sky-data.js')


def ra360(lon):
    return round(lon % 360, 3)


def main(src):
    load = lambda n: json.load(open(os.path.join(src, n), encoding='utf-8'))

    # ---- stars (Hipparcos, mag <= 5.5), sorted bright → faint ----
    stars = [f for f in load('stars.6.json')['features'] if f['properties']['mag'] <= MAG_LIMIT]
    stars.sort(key=lambda f: f['properties']['mag'])
    flat, hip_index = [], {}
    for i, f in enumerate(stars):
        lon, lat = f['geometry']['coordinates']
        try:
            bv = round(float(f['properties'].get('bv') or 0.6), 2)
        except ValueError:
            bv = 0.6
        flat += [ra360(lon), round(lat, 3), round(f['properties']['mag'], 2), bv]
        hip_index[str(f['id'])] = i

    # ---- star names: Korean proper names for catalog stars ----
    names = []
    for hip, n in load('starnames.json').items():
        if hip not in hip_index:
            continue
        idx = hip_index[hip]
        mag = flat[idx * 4 + 2]
        ko = n.get('ko') or ''
        en = n.get('name') or ''
        bayer = (n.get('bayer') or n.get('flam') or '')
        if not (ko or en):
            continue
        # keep proper-named stars reasonably bright so labels stay readable
        if mag > 3.2 and not ko:
            continue
        names.append([int(hip), idx, ko or en, en, (bayer + ' ' + n.get('c', '')).strip()])
    names.sort(key=lambda r: flat[r[1] * 4 + 2])

    # ---- constellations: names, label position, stick-figure lines ----
    cons = {}
    for f in load('constellations.json')['features']:
        p = f['properties']
        lon, lat = f['geometry']['coordinates']
        cons[f['id']] = {'ko': p.get('ko') or p['name'], 'en': p.get('en') or p['name'],
                         'la': p['name'], 'gen': p.get('gen', ''), 'rank': int(p.get('rank', 3)),
                         'lbl': [ra360(lon), round(lat, 2)], 'lines': []}
    for f in load('constellations.lines.json')['features']:
        c = cons.get(f['id'])
        if not c:
            continue
        for line in f['geometry']['coordinates']:
            seg = []
            for lon, lat in line:
                seg += [ra360(lon), round(lat, 3)]
            c['lines'].append(seg)

    # ---- Milky Way: rasterise the 5 nested outlines onto a 2° grid ----
    mw_polys = []
    for level, f in enumerate(load('milkyway.json')['features']):
        g = f['geometry']
        polys = g['coordinates'] if g['type'] == 'MultiPolygon' else [g['coordinates']]
        for poly in polys:
            mw_polys.append((level + 1, poly))

    def inside(ring, x, y):
        c = False
        n = len(ring)
        j = n - 1
        for i in range(n):
            xi, yi = ring[i]
            xj, yj = ring[j]
            if (yi > y) != (yj > y) and x < (xj - xi) * (y - yi) / (yj - yi + 1e-12) + xi:
                c = not c
            j = i
        return c

    mw = []
    step = 2.0
    dec = -89.0
    while dec < 90:
        ra_step = step / max(0.2, math.cos(math.radians(dec)))
        ra = -180.0
        while ra < 180:
            w = 0
            for level, poly in mw_polys:
                if inside(poly[0], ra, dec) and not any(inside(h, ra, dec) for h in poly[1:]):
                    w += 1
            if w:
                mw += [ra360(ra), round(dec, 1), w]
            ra += ra_step
        dec += step

    data = {'v': 1, 'src': 'd3-celestial 0.7.35 (Hipparcos, BSD-3-Clause)',
            'stars': flat, 'names': names, 'cons': cons, 'mw': mw}
    js = ('/* Generated by tools/build_sky_data.py — do not edit by hand.\n'
          ' * Star, constellation-line and Milky Way data: d3-celestial by Olaf Frohn (BSD-3-Clause). */\n'
          'window.SKY_DATA=' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(js)
    print(f'stars={len(stars)} names={len(names)} cons={len(cons)} mw={len(mw)//3} bytes={len(js.encode())}')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else 'package/data')
